### ISSUE TITLE
Search results include matches within a word

### ISSUE THREAD

**Issue by paul-mediakitchen** [cgkineo/adapt-search#11]
For example searching for the word "hang" brings up results for "change" This is not ideal and in an ideal world there would be a setting to select whether the search should do this or not.

**Comment by oliverfoster** [comment]
it does three things in particular:

1: it returns any word in the course, which is the beginning of the word searched
   course: one      search: oneness
   course: manufacture      search: manufacturer
   course: language        search: languages

2: it returns any word in the course, which contains the word searched
  course: antidisestablishmentarianism     search: establistment
  course: tax-exempt   search: tax
  course: paper-thin   search: thin

3: it returns exact matches (case insensitive)
         
shall i make a boolean option for the first two?

**Comment by brian-learningpool** [comment]
HI @oliverfoster, yes, I think a boolean option to disable search within word (options 1 and 2 above) would be a really useful feature.

**Comment by oliverfoster** [comment]
@paul-mediakitchen & @brian-learningpool  would you check that the pr matching your expectations?
