### ISSUE TITLE
Ability to exclude specific articles, blocks or components from search results

### ISSUE THREAD

**Issue by paul-mediakitchen** [cgkineo/adapt-search#12]
It would be great for each article, block and component to have a drop down to choose where to exclude it from the search results. A simple true/false drop down would suffice.

In my particular scenario I have a load of buttons (hyperlinks) that all include important keywords and the search results is displaying all these buttons and polluting the results.

**Comment by oliverfoster** [comment]
just awaiting a test or two, fix is almost in,

**Comment by moloko** [comment]
https://youtu.be/-ITMRHJnaJY?t=46 ;-)

**Comment by oliverfoster** [comment]
that's one of m'favourite songs

**Comment by oliverfoster** [comment]
can someone have a see if this works in the AT?
