### ISSUE TITLE
Ability to search in titles only

### ISSUE THREAD

**Issue by paul-mediakitchen** [cgkineo/adapt-search#13]
Be a nice addition to select searching within titles only.

**Comment by oliverfoster** [comment]
You can already do this. just need to modify ``_searchAttributes`` https://github.com/cgkineo/adapt-search/blob/master/example.json#L32 to contain only:

```
        {
            "_attributeName": "displayTitle", //where this is the name of the attribute you which to search
            "_level": 1,
            "_allowTextPreview": true
        },
```

**Comment by oliverfoster** [comment]
could you test and let me know?

**Comment by oliverfoster** [comment]
did you need this in the authoring tool? it just occurred to me - whilst reading the schema - that this ain't possible.
