### ISSUE TITLE
Search ignores trickle and locked content

### ISSUE THREAD

**Issue by brian-learningpool** [cgkineo/adapt-search#14]
A course-wide search takes places regardless of whether menu items are locked, whether trickle is enabled, i.e. the search results may show entries that the user should not have access to yet.

**Comment by oliverfoster** [comment]
the trickle issue is a bit difficult as it doesn't currently notify anything else that it intends to (or is currently) step locking - gonna have to have a think on that one.

locking is a goer. i'll put that in in a bit.

**Comment by oliverfoster** [comment]
should all be fine with the locked content now @brian-learningpool

**Comment by oliverfoster** [comment]
gonna leave this open until i can figure out how to do trickle

**Comment by oliverfoster** [comment]
this is particularly difficult as neither assessment nor trickle mark their respective components / blocks when the course starts up... might be worth reconsidering the approach of having extensions configure their pages when the page is rendered.

**Comment by oliverfoster** [comment]
need to retest with new trickle

**Comment by oliverfoster** [comment]
substantially broken with branching and new trickle
