### ISSUE TITLE
Search doesn't support Chinese characters

### ISSUE THREAD

**Issue by samumist** [cgkineo/adapt-search#15]
Having the following Chinese characters in a text component body, then search for either `好好学习`, or `好好`, or `好`, found none.

It is also set as the `title` of the text component, not `display title`.

```
好好学习
```
It is the same when set these characters in the json as keywords.

**Comment by samumist** [comment]
![screenshot 2016-10-12 17 33 55](https://cloud.githubusercontent.com/assets/3883086/19305129/290c03ac-90a2-11e6-9f57-a406bb1090c8.jpg)

some further info, when typed `好好x` (as shown in the screenshot), the search result shows up with the `title`. But search for `好好a`, or `好好b` etc returned nothing.

**Comment by moloko** [comment]
@samumist we might need some help from you on this one as our Chinese language skills are a bit lacking!

**Comment by samumist** [comment]
Absolutely. Just let me know if there's anything I can help with.

**Comment by oliverfoster** [comment]
can you test this @samumist ?

you might still have to set the minimum word length to 1 if you want to allow searching for a single word-character.

**Comment by samumist** [comment]
Yes, it is fixed! 
Yes, I have to set the minimum word length to 1 to search for a single character. But single character doesn't really mean a lot in Chinese.

Great Job!

**Comment by oliverfoster** [comment]
cool, thanks for testing.

**Comment by samumist** [comment]
There are still some things not quite right. If you have more words, only the first word that can be searched with 1 or 2 word. Others you need at least 4 word to be able to search them. 

For example, I have the following words in my text component body.

```
好好学习，这个世界。外交部政府部门，救灾减灾。hello World!
```

If I search `好` or ｀好好`, the result comes out fine (as in screenshot 1). But when I search `这个` or `世界` or `这个世`(as in screenshot 2), found nothing. If I search `这个世界`, 4 words,  it shows up. Please see screen attached.

**ScreenShot 1: search with "好"**
![screenshot 2016-10-13 18 35 52](https://cloud.githubusercontent.com/assets/3883086/19346305/45b6bf1e-9175-11e6-94d5-906cc4e6875c.jpg)

**ScreenShot 2: search with "这个世"**
![screenshot 2016-10-13 18 35 40](https://cloud.githubusercontent.com/assets/3883086/19346323/5565dba2-9175-11e6-864b-7fa17b78794f.jpg)

**ScreenShot 3: search with "这个世界"**
![screenshot 2016-10-13 18 35 23](https://cloud.githubusercontent.com/assets/3883086/19346365/841b47de-9175-11e6-9d08-d207de7969fa.jpg)

**Comment by oliverfoster** [comment]
take two, it was word boundaries this time. your comma and dot weren't seen as word boundaries, same branch

**Comment by samumist** [comment]
Fixed the search result.

One small problem, which doesn't really matter that much, is the search highlight. If you search `好好` or `学习`, the search result highlight `好好学习`. But if you search `这个`, it highlights the sentence until next punctuation mark.

![screenshot 2016-10-13 20 10 18](https://cloud.githubusercontent.com/assets/3883086/19348590/40cc6240-9181-11e6-84cc-c6f34c9da9ce.jpg)
![screenshot 2016-10-13 20 10 32](https://cloud.githubusercontent.com/assets/3883086/19348592/427bcc70-9181-11e6-9cae-4b9783bf4335.jpg)


** Search highlight sentence rather than search word**
![screenshot 2016-10-13 20 10 53](https://cloud.githubusercontent.com/assets/3883086/19348598/48d0c472-9181-11e6-86de-cffce5e11ad4.jpg)
![screenshot 2016-10-13 20 11 16](https://cloud.githubusercontent.com/assets/3883086/19348602/4c02168c-9181-11e6-8ae1-b4b2f6c9eae3.jpg)

**Comment by oliverfoster** [comment]
yea, it's just highlighting the whole section it found in between 'word boundaries'(european ones). it does look strange i admit. it is still treating each section as a european word. and it's highlighting what it has found, not what you have searched for. 

i'd have to allow it to switch so that each character a unit on its own.

the only way to do that would be with a boolean flag because i've no idea which other languages / unicode ranges it would apply to.

**Comment by samumist** [comment]
It's not a problem. Maybe we should just leave it as it is now. 
Regular users may never notice the difference of the search highlight.

**Comment by oliverfoster** [comment]
Ok. If it does become a problem, it shouldn't be too hard to solve. Let me know,

**Comment by samumist** [comment]
Thanks very much, Ollie!
