### ISSUE TITLE
Add some defensive programming for the new _isEnabled property

### ISSUE THREAD

**Issue by brian-learningpool** [cgkineo/adapt-search#23]
The new `_isEnabled` property is very useful, but I think it would a good idea to add some defensive coding to check that the property exists, not that it is just `false` before disabling functionality.

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-search/blob/master/js/search-algorithm.js#L139
https://github.com/cgkineo/adapt-search/blob/master/js/search-algorithm.js#L220

it is always enabled unless the property is false. the existence check is uneccesary as it'll be equal to ``undefined`` if it doesn't exist and therefore not equal to false.

i'm missing something. if it doesn't exist what should it do?

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-search/blob/master/js/search-algorithm.js#L139 < this line makes sense, it just doesn't need the ``_.has(config._isEnabled)``

**Comment by oliverfoster** [comment]
cool, i'm happy with that one, thanks dude
