### ISSUE TITLE
Bring into a menu?

### ISSUE THREAD

**Issue by hmaffin** [cgkineo/adapt-search#26]
Would it be technically possible to have this search extension appear on the menu page in a component rather than in the drawer, so that the search is visible on the homepage when you launch a course? And to maybe put the search results in a pop up window?

**Comment by moloko** [comment]
that would be a totally new plugin really...

**Comment by hmaffin** [comment]
Yeah sorry I knew that - just wondered if it were technically possible rather than making a change to this one. Perhaps better for gitter chat than an issue for this one. Thought maybe I'd fork it and have a play but no idea where to start!
