### ISSUE TITLE
Problem with switching language on a multi-language course

### ISSUE THREAD

**Issue by brian-learningpool** [cgkineo/adapt-search#29]
There is a `listenToOnce` on `app:dataReady` here:
https://github.com/cgkineo/adapt-search/blob/master/js/search-algorithm.js#L138

If you have a multi-language course and change language mid-way through, the Search extension disappears from the Drawer. `app:dataReady` will fire any time a language switch occurs, so should this be changed to a `listenTo` instead?

**Comment by moloko** [comment]
certainly sounds like it should be

**Comment by brian-learningpool** [comment]
Fixed in 2.1.3. 👍
