### ISSUE TITLE
Escaped tags are not replaced before results are rendered

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [cgkineo/adapt-search#45]
The `stripTags` function currently performs a regex replace for opening and closing tags. This needs expanded to replace escaped tags to prevent the `renderResults` from reintroducing them to the page.

**Comment by moloko** [comment]
could you provide a sample so as to make it easier to test your PR?

**Comment by cahirodoherty-learningpool** [comment]
[sample.zip](https://github.com/cgkineo/adapt-search/files/3472234/sample.zip)

**Comment by moloko** [comment]
fixed in 07fb1e7
