### ISSUE TITLE
Any plans to release this to the Authoring Tool?

### ISSUE THREAD

**Issue by hmaffin** [cgkineo/adapt-search#5]
I think people are crying out for this - what a great extension it would be!

**Comment by oliverfoster** [comment]
just rewriting the algorithm for it, we'll know soon if it's ready

**Comment by hmaffin** [comment]
*skip* :) Cheers Oli

**Comment by mediakitchen** [comment]
Any update on this?

**Comment by oliverfoster** [comment]
Not just yet. It's going through testing in a project at the moment.

**Comment by mediakitchen** [comment]
Ok thanks Oli. I hope the testing goes well. I have a project that desparately needs this search functionality.

**Comment by oliverfoster** [comment]
If you're keen, you can try the branch "new" it should work fine with v2 of the framework.

**Comment by mediakitchen** [comment]
Thanks Oli. I tried the "new" branch but had errors when building:

Running "concat:less" (concat) task
File src/less/adapt.less created.

Running "less:dist" (less) task
>> NameError: variable @drawer-color-inverted is undefined in src/less/adapt.less on line 3645, column 38:
>> 3644                 color: @drawer-item-text-color;
>> 3645             border-bottom: 1px solid darken(@drawer-color-inverted, 10%);
>> 3646             width: 100%;
Warning: Error compiling src/less/adapt.less

**Comment by hmaffin** [comment]
I'm using it in the AT - seems to work great. Only thing is I have to be good and name all my components now or in the search results it just comes up with "Component Title" ;)

Thanks team!

**Comment by moloko** [comment]
no problem at all @hmaffin thanks for letting us know

**Comment by paul-mediakitchen** [comment]
Helen, yes that is annoying and adding the ability to exclude or include each article, block or component from the search results would remove that issue perhaps. Fingers crossed we may see this functionality soon - I know that someone may be working on it at the moment.

**Comment by hmaffin** [comment]
I think you can remove certain components and things from the search results can't you - in the search settings for each part? *checks* ah no - there's just a "keyword" box - although I have no idea what that is used for! Just adding the "true and false" in with this for each component like you can with pageLevelProgress would be awesome!

**Comment by paul-mediakitchen** [comment]
The keyword box is to add additional keywords. So if I had a text component with the following text:

"I like programming."

I could add the following keywords to make this component appear in the search results if say I typed in "coding" or "programming".

Without the keywords it would not come up when I searched for "coding"

code, nerd, coding, programing (typo!)

**Comment by hmaffin** [comment]
oooooh that's very neat!!!
