### ISSUE TITLE
Does this work with V2 of the Adapt Framework?

### ISSUE THREAD

**Issue by paul-mediakitchen** [cgkineo/adapt-search#6]

**Comment by oliverfoster** [comment]
Please see https://github.com/cgkineo/adapt-search/issues/5

We'll let you know late January.

**Comment by mediakitchen** [comment]
Managed to get this working with the master and V2 of the Adapt Framework. The only issue I had was that when there were resources included the search field did not appear in the drawer. Removing the resources from course.json caused the search elements to display.

**Comment by oliverfoster** [comment]
could you please retest? works fine for me, with or without resources.

**Comment by oliverfoster** [comment]
i'm closing as i've seen other people use in vanilla v2 adapt + resources with no issue. please reopen if still a problem.
