### ISSUE TITLE
Issue with all components when ... is only content in body or other areas

### ISSUE THREAD

**Issue by mike-st** [cgkineo/adapt-search#68]
### Subject of the issue/enhancement/features
When using only ... in a component body, or item text it breaks the Search with an error and the course can not search any more. 

### Your environment
FW 5.28.9
Chrome/Edge/Safari/Firefox
PC/MAC

### Steps to reproduce
Type only ... in any component's body area or any where else and I get an error.

### Expected behaviour
Shouldn't have an error when using triple dots (...)

### Actual behaviour
I get the following error in the screenshot below...

### Screenshots (if you can)
![searchError](https://user-images.githubusercontent.com/10455453/229911033-d7ae540c-0841-4bbf-a4ae-d0a7d35aa63e.jpg)

**Comment by swashbuck** [comment]
Can generally be replicated by using one or more non-alphanumeric characters like hash, question mark, comma, period, etc.

```
"body": "."
```
Or
```
"body": "?"
```
etc.
