### ISSUE TITLE
@quaternary-colour is undefined

### ISSUE THREAD

**Issue by brian-learningpool** [cgkineo/adapt-search#9]
The `master` branch throws an error on this LESS variable.

**Comment by brian-learningpool** [comment]
Actually, I see why this is happening.  We really should come up with that list of required LESS variables(!)

**Comment by oliverfoster** [comment]
Theme not right? Or did I do summat?

**Comment by brian-learningpool** [comment]
Sorry for the late reply.  It was a custom theme which didn't define the variable.
